# Form implementation generated from reading ui file 'ui/mainUI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(380, 323)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/../resource/logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("border-radius: 5px;    \n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.login = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.login.setGeometry(QtCore.QRect(100, 60, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.login.setFont(font)
        self.login.setStyleSheet("border-radius: 4px;    \n"
"")
        self.login.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.login.setObjectName("login")
        self.password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.password.setGeometry(QtCore.QRect(100, 130, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.password.setFont(font)
        self.password.setStyleSheet("border-radius: 4px;\n"
"")
        self.password.setText("")
        self.password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.password.setObjectName("password")
        self.logIn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.logIn.setGeometry(QtCore.QRect(270, 230, 80, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.logIn.setFont(font)
        self.logIn.setStyleSheet("border-radius: 5px;\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgba(184, 184, 184,0.5);\n"
"\n"
"")
        self.logIn.setObjectName("logIn")
        self.status = QtWidgets.QLabel(parent=self.centralwidget)
        self.status.setGeometry(QtCore.QRect(60, 10, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.status.setFont(font)
        self.status.setStyleSheet("color: rgb(255, 10, 75);\n"
"")
        self.status.setText("")
        self.status.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.status.setObjectName("status")
        self.passShow = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.passShow.setGeometry(QtCore.QRect(231, 190, 121, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.passShow.setFont(font)
        self.passShow.setObjectName("passShow")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 380, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.settings = QtGui.QAction(parent=MainWindow)
        self.settings.setObjectName("settings")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.login.setPlaceholderText(_translate("MainWindow", "Kullanıcı adı"))
        self.password.setPlaceholderText(_translate("MainWindow", "Şifre"))
        self.logIn.setText(_translate("MainWindow", "Giriş Yap"))
        self.passShow.setText(_translate("MainWindow", "Şifreyi göster"))
        self.settings.setText(_translate("MainWindow", "Settings"))
