# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CommentLikerPanel(object):
    def setupUi(self, CommentLikerPanel):
        CommentLikerPanel.setObjectName("CommentLikerPanel")
        CommentLikerPanel.resize(583, 495)
        self.centralwidget = QtWidgets.QWidget(parent=CommentLikerPanel)
        self.centralwidget.setObjectName("centralwidget")
        self.commentBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.commentBox.setGeometry(QtCore.QRect(320, 10, 251, 331))
        self.commentBox.setObjectName("commentBox")
        self.commentsList = QtWidgets.QComboBox(parent=self.commentBox)
        self.commentsList.setEnabled(False)
        self.commentsList.setGeometry(QtCore.QRect(10, 30, 231, 291))
        self.commentsList.setEditable(False)
        self.commentsList.setIconSize(QtCore.QSize(32, 32))
        self.commentsList.setModelColumn(0)
        self.commentsList.setObjectName("commentsList")
        self.getComments = QtWidgets.QPushButton(parent=self.centralwidget)
        self.getComments.setGeometry(QtCore.QRect(419, 350, 151, 25))
        self.getComments.setObjectName("getComments")
        self.comment = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.comment.setGeometry(QtCore.QRect(9, 10, 301, 331))
        self.comment.setObjectName("comment")
        self.postLink = QtWidgets.QLineEdit(parent=self.comment)
        self.postLink.setGeometry(QtCore.QRect(10, 34, 288, 31))
        self.postLink.setObjectName("postLink")
        self.terminal = QtWidgets.QPlainTextEdit(parent=self.comment)
        self.terminal.setGeometry(QtCore.QRect(10, 80, 288, 241))
        self.terminal.setObjectName("terminal")
        self.start = QtWidgets.QPushButton(parent=self.centralwidget)
        self.start.setGeometry(QtCore.QRect(10, 350, 151, 25))
        self.start.setObjectName("start")
        CommentLikerPanel.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=CommentLikerPanel)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 583, 22))
        self.menubar.setObjectName("menubar")
        CommentLikerPanel.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=CommentLikerPanel)
        self.statusbar.setObjectName("statusbar")
        CommentLikerPanel.setStatusBar(self.statusbar)

        self.retranslateUi(CommentLikerPanel)
        QtCore.QMetaObject.connectSlotsByName(CommentLikerPanel)

    def retranslateUi(self, CommentLikerPanel):
        _translate = QtCore.QCoreApplication.translate
        CommentLikerPanel.setWindowTitle(_translate("CommentLikerPanel", "MainWindow"))
        self.commentBox.setTitle(_translate("CommentLikerPanel", "Comments"))
        self.getComments.setText(_translate("CommentLikerPanel", "Commentleri Yükle"))
        self.comment.setTitle(_translate("CommentLikerPanel", "Comment link"))
        self.postLink.setPlaceholderText(_translate("CommentLikerPanel", "https://"))
        self.start.setText(_translate("CommentLikerPanel", "Başlat"))
